{% set name = "omero-marshal" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/omero_marshal-{{ version }}.tar.gz
  sha256: 5d88d0cc1d2360863ccc06156c7e69910ed10013e3ff731662d574d54b0faf11

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - omero-py
    - python >={{ python_min }}

test:
  imports:
    - omero_marshal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ome/omero-marshal
  summary: OMERO Marshal
  license: GPL-2.0
  license_file: license.md

extra:
  recipe-maintainers:
    - joshmoore
    - marimeireles
